project:
  type: website

execute:
  freeze: auto

website:
  title: "AstroEsteban" 
  site-url:  https://astroesteban.github.io
  description: "Musings on spacecraft autonomy and flight software"
  favicon: favicon/favicon.ico
  image: rocket.png
  navbar:
    right:
      - text: Blog
        href: blog.qmd 
      - text: Archive
        href: archive.qmd

format:
  html:
    theme: theme.scss