project:
  type: website

website:
  title: "The Bit Flip" 
  site-url:  https://astroesteban.github.io
  description: "Musings on spacecraft autonomy and flight software"
  navbar:
    right:
      - text: Blog
        href: blog.qmd 
      - icon: github
        href: https://github.com/astroesteban
      - icon: twitter
        href: https://twitter.com/astroesteban
      - icon: linkedin
        href: https://www.linkedin.com/in/estebanduran

format:
  html:
    theme: theme.scss