project:
  type: website

website:
  title: "The Bit Flip" 
  site-url:  https://astroesteban.github.io
  description: "Musings on spacecraft autonomy and flight software"
  navbar:
    right:
      - text: Blog
        href: blog.qmd 
      - text: Archive
        href: archive.qmd

format:
  html:
    theme: theme.scss